import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "lenis/react";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased outfit`}
      >
         {/* <ReactLenis root /> */}
         <Providers>{children}</Providers>
      </body>
    </html>
  );
}
